apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensors
  name: sensor-home-rpi
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-home-rpi
  template:
    metadata:
      labels:
        app: sensor-home-rpi
    spec:
      tolerations:
      - key: arhat.dev/namespace
        value: edge
      nodeSelector:
        arhat.dev/name: home-rpi
      volumes:
      - name: dev-dir
        hostPath:
          path: /dev
      - name: collection-dir
        hostPath:
          path: /run/metrics/textfile
      containers:
      - image: jeffctor/rpi-examples-armv7:latest
        imagePullPolicy: IfNotPresent
        name: sensor-reader
        volumeMounts:
        - name: collection-dir
          mountPath: /var/lib/textfile-collections
        - name: dev-dir
          mountPath: /dev
        securityContext:
          # required to manipulate GPIO
          privileged: true
